# Generated by Django 3.1.3 on 2023-11-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_size_type', models.CharField(choices=[('US', 'US Shoe Size Measuring System'), ('EU', 'EU Shoe Size Measuring System'), ('UK', 'UK Shoe Size Measuring System')], default='US', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shoe_sizes', models.ManyToManyField(to='shoes.ShoeSize')),
                ('shoe_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes.shoetype')),
            ],
        ),
    ]
